'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, ArrowUpRight, Check, ChevronDown, GitFork, Terminal, Search, Code2 } from 'lucide-react'
import { Navbar } from '@/components/navbar'

const steps = [['Fork & clone','git clone https://github.com/YOUR-USERNAME/Formicx.git',GitFork],['Set up locally','python -m venv venv && pip install -e .[dev]',Terminal],['Pick an issue','Browse open issues tagged good first issue',Search],['Develop & test','pytest unit verification',Code2],['Push & create PR','git push origin feat/my-feature',ArrowUpRight]] as const
const issues = [['Add --json output to resource tables','CLI'],['Colorize CPU & memory thresholds','CLI'],['Build systemd service supervisor','OS Integration'],['Add SDK lifecycle callback docs','SDK']]
export default function ContributePage() {
 const [filter,setFilter]=useState('All'); const [open,setOpen]=useState<number | null>(0); const filters=['All','Beginner','CLI','SDK','OS Integration'];
 return <><Navbar/><main className="contribute-page"><div className="container"><Link href="/" className="back-link"><ArrowLeft/> Back to Formicx</Link><div className="contribute-hero"><p className="eyebrow">THE CONTRIBUTION HUB</p><h1>Ship the future<br/><em>with us.</em></h1><p>Formicx is early, open, and ready for your ideas. Whether you are here to fix a typo or build a new subsystem, there is a place for you.</p></div><section className="steps-section"><div className="section-heading"><p className="eyebrow">THE PATH TO MERGE</p><h2>Five steps. <em>One community.</em></h2></div><div className="steps-grid">{steps.map(([title,code,Icon],i)=><div className="step" key={title}><div className="step-index">0{i+1}<Icon/></div><h3>{title}</h3><code>{code}</code>{i<4&&<span className="step-connector">→</span>}</div>)}</div></section><section className="hub-grid"><div><div className="section-heading"><p className="eyebrow">START HERE</p><h2>Find your <em>first issue.</em></h2></div><div className="filter-row">{filters.map(item=><button className={filter===item?'selected':''} key={item} onClick={()=>setFilter(item)}>{item}</button>)}</div><div className="hub-issues">{issues.filter(([_,tag])=>filter==='All'||filter===tag||filter==='Beginner').map(([title,tag],i)=><a href="https://github.com/Abbilaash/Formicx/issues" target="_blank" rel="noreferrer" className="hub-issue" key={title}><span className="issue-label">{filter==='Beginner'?'BEGINNER':tag.toUpperCase()}</span><h3>{title}</h3><span>good first issue · #{42-i}</span><ArrowUpRight/></a>)}</div></div><div className="guidelines"><p className="eyebrow">GOOD TO KNOW</p><h2>Contributor <em>guidelines.</em></h2>{['Code style','Commit conventions','PR review process'].map((title,i)=><div className="accordion" key={title}><button onClick={()=>setOpen(open===i?null:i)}><span>{title}</span>{open===i?<Check/>:<ChevronDown/>}</button>{open===i&&<p>{i===0?'Keep Python clean, typed, and easy to read. Run the formatter and test suite before opening a PR.':i===1?'Use conventional commits like feat(cli): add json output so the history stays searchable.':'Every PR gets a thoughtful review. Be open to feedback and keep changes focused.'}</p>}</div>)}</div></section></div></main></>
}
